default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: admin
  host: localhost
  port: 5432

development:
 <<: *default
 database: gemini-dev

test:
 <<: *default
 database:

production:
 <<: *default
 database:
